set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include/SDL")

#64 bits
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(SDL2_LIBRARIES_PATH "${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x64/")
    set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x64/SDL2main.lib")
   
#32 bits
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(SDL2_LIBRARIES_PATH "${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x86/")
    set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/SDL/x86/SDL2main.lib")
endif()
